import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

const CLI_PATH = path.join(__dirname, '..', 'dist', 'cli.js');

function runCLI(args: string, cwd: string): string {
  try {
    return execSync(`node "${CLI_PATH}" ${args}`, {
      cwd,
      encoding: 'utf-8',
      timeout: 10000,
    });
  } catch (error) {
    // Return stderr + stdout for commands that exit non-zero
    const e = error as { stdout?: string; stderr?: string };
    return (e.stdout || '') + (e.stderr || '');
  }
}

function createTmpDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'envrizz-cli-test-'));
  // Init a git repo so init can install hooks
  execSync('git init', { cwd: dir, stdio: 'ignore' });
  return dir;
}

describe('CLI: generate-example', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = createTmpDir();
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('generates .env.example with common keys from multiple files', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000\nDB_URL=postgres://localhost\nAPI_KEY=secret');
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'PORT=8080\nDB_URL=postgres://staging\nSTRIPE_KEY=sk_test');
    fs.writeFileSync(path.join(tmpDir, '.env.production'), 'PORT=80\nDB_URL=postgres://prod\nAPI_KEY=prod_key');

    const output = runCLI('generate-example', tmpDir);

    expect(output).toContain('Generated .env.example with 2 keys');
    expect(output).toContain('PORT');
    expect(output).toContain('DB_URL');
    expect(output).not.toContain('API_KEY');
    expect(output).not.toContain('STRIPE_KEY');

    const example = fs.readFileSync(path.join(tmpDir, '.env.example'), 'utf-8');
    expect(example).toContain('PORT=');
    expect(example).toContain('DB_URL=');
    expect(example).not.toContain('API_KEY');
  });

  it('generates .env.example with all keys from a single file', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000\nHOST=localhost');

    const output = runCLI('generate-example', tmpDir);

    expect(output).toContain('Generated .env.example with 2 keys');

    const example = fs.readFileSync(path.join(tmpDir, '.env.example'), 'utf-8');
    expect(example).toContain('PORT=');
    expect(example).toContain('HOST=');
  });

  it('reports when no .env files exist', () => {
    const output = runCLI('generate-example', tmpDir);
    expect(output).toContain('No .env files found');
    expect(fs.existsSync(path.join(tmpDir, '.env.example'))).toBe(false);
  });

  it('reports when no common keys exist', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000');
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'API_KEY=secret');

    const output = runCLI('generate-example', tmpDir);
    expect(output).toContain('No common keys found');
  });

  it('excludes .env.example and .env.sample from input', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000\nHOST=localhost');
    fs.writeFileSync(path.join(tmpDir, '.env.example'), 'OLD_KEY=');
    fs.writeFileSync(path.join(tmpDir, '.env.sample'), 'SAMPLE_KEY=');

    const output = runCLI('generate-example', tmpDir);

    // Should only look at .env, not .env.example or .env.sample
    expect(output).toContain('Generated .env.example with 2 keys');
    const example = fs.readFileSync(path.join(tmpDir, '.env.example'), 'utf-8');
    expect(example).not.toContain('OLD_KEY');
    expect(example).not.toContain('SAMPLE_KEY');
  });

  it('overwrites existing .env.example', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000');
    fs.writeFileSync(path.join(tmpDir, '.env.example'), 'STALE_KEY=');

    runCLI('generate-example', tmpDir);

    const example = fs.readFileSync(path.join(tmpDir, '.env.example'), 'utf-8');
    expect(example).toContain('PORT=');
    expect(example).not.toContain('STALE_KEY');
  });

  it('includes header comments in generated file', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000');

    runCLI('generate-example', tmpDir);

    const example = fs.readFileSync(path.join(tmpDir, '.env.example'), 'utf-8');
    expect(example).toContain('# Generated by envrizz');
    expect(example).toContain('# Keys common to:');
    expect(example).toContain('# Copy this file to .env');
  });
});

describe('CLI: diff', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = createTmpDir();
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('shows common keys across files', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000\nDB=local');
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'PORT=8080\nDB=staging\nDEBUG=true');

    const output = runCLI('diff', tmpDir);

    expect(output).toContain('Common to all files (2)');
    expect(output).toContain('PORT');
    expect(output).toContain('DB');
  });

  it('shows missing keys per file', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000\nAPI_KEY=secret');
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'PORT=8080\nREDIS_URL=redis://local');

    const output = runCLI('diff', tmpDir);

    expect(output).toContain('Missing from .env');
    expect(output).toContain('REDIS_URL');
    expect(output).toContain('Missing from .env.local');
    expect(output).toContain('API_KEY');
  });

  it('shows keys unique to each file', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000\nDEBUG=true');
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'PORT=8080\nMY_THING=yes');
    fs.writeFileSync(path.join(tmpDir, '.env.production'), 'PORT=80\nPROD_SECRET=abc');

    const output = runCLI('diff', tmpDir);

    expect(output).toContain('Only in .env');
    expect(output).toContain('DEBUG');
    expect(output).toContain('Only in .env.local');
    expect(output).toContain('MY_THING');
    expect(output).toContain('Only in .env.production');
    expect(output).toContain('PROD_SECRET');
  });

  it('shows all synced message when files match', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000\nHOST=localhost');
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'PORT=8080\nHOST=staging');

    const output = runCLI('diff', tmpDir);

    expect(output).toContain('All .env files have the same keys');
  });

  it('handles single file gracefully', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000');

    const output = runCLI('diff', tmpDir);

    expect(output).toContain('Only one .env file found');
    expect(output).toContain('Nothing to compare');
  });

  it('reports when no .env files exist', () => {
    const output = runCLI('diff', tmpDir);
    expect(output).toContain('No .env files found');
  });

  it('shows (none) when no common keys exist', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000');
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'API_KEY=secret');

    const output = runCLI('diff', tmpDir);

    expect(output).toContain('Common to all files (0)');
    expect(output).toContain('(none)');
  });
});

describe('CLI: init (integration)', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = createTmpDir();
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('creates envrizz.json config file', () => {
    runCLI('init --project test-project', tmpDir);

    const configPath = path.join(tmpDir, 'envrizz.json');
    expect(fs.existsSync(configPath)).toBe(true);

    const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    expect(config.projectName).toBe('test-project');
    expect(config.exclude).toEqual(['.env.example', '.env.sample']);
    expect(config.include).toEqual(['.env', '.env.*']);
  });

  it('adds npm scripts to package.json', () => {
    fs.writeFileSync(path.join(tmpDir, 'package.json'), JSON.stringify({
      name: 'test',
      scripts: { build: 'tsc' },
    }, null, 2));

    runCLI('init --project test-project', tmpDir);

    const pkg = JSON.parse(fs.readFileSync(path.join(tmpDir, 'package.json'), 'utf-8'));
    expect(pkg.scripts['env:push']).toBe('envrizz push');
    expect(pkg.scripts['env:pull']).toBe('envrizz pull');
    expect(pkg.scripts.build).toBe('tsc'); // preserved
  });

  it('does not overwrite existing env:push script', () => {
    fs.writeFileSync(path.join(tmpDir, 'package.json'), JSON.stringify({
      name: 'test',
      scripts: { 'env:push': 'custom-push' },
    }, null, 2));

    runCLI('init --project test-project', tmpDir);

    const pkg = JSON.parse(fs.readFileSync(path.join(tmpDir, 'package.json'), 'utf-8'));
    expect(pkg.scripts['env:push']).toBe('custom-push');
  });

  it('installs pre-commit hook for generate-example', () => {
    runCLI('init --project test-project', tmpDir);

    const hookPath = path.join(tmpDir, '.git', 'hooks', 'pre-commit');
    expect(fs.existsSync(hookPath)).toBe(true);

    const hook = fs.readFileSync(hookPath, 'utf-8');
    expect(hook).toContain('envrizz generate-example');
    expect(hook).toContain('git add .env.example');

    // Check executable
    const stats = fs.statSync(hookPath);
    const mode = (stats.mode & 0o777).toString(8);
    expect(mode).toBe('755');
  });

  it('appends to existing pre-commit hook without overwriting', () => {
    const hookDir = path.join(tmpDir, '.git', 'hooks');
    fs.mkdirSync(hookDir, { recursive: true });
    fs.writeFileSync(path.join(hookDir, 'pre-commit'), '#!/bin/sh\nnpm run lint\n');
    fs.chmodSync(path.join(hookDir, 'pre-commit'), '755');

    runCLI('init --project test-project', tmpDir);

    const hook = fs.readFileSync(path.join(hookDir, 'pre-commit'), 'utf-8');
    expect(hook).toContain('npm run lint');
    expect(hook).toContain('envrizz generate-example');
  });

  it('does not duplicate hook on repeated init', () => {
    runCLI('init --project test-project', tmpDir);
    runCLI('init --project test-project', tmpDir);

    const hook = fs.readFileSync(path.join(tmpDir, '.git', 'hooks', 'pre-commit'), 'utf-8');
    const matches = hook.match(/envrizz generate-example/g);
    expect(matches).toHaveLength(1);
  });
});

describe('CLI: list (integration)', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = createTmpDir();
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('lists variables from all .env files', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000\nHOST=localhost');
    fs.writeFileSync(path.join(tmpDir, '.env.local'), 'API_KEY=secret');

    const output = runCLI('list', tmpDir);

    expect(output).toContain('.env:');
    expect(output).toContain('PORT=3000');
    expect(output).toContain('HOST=localhost');
    expect(output).toContain('.env.local:');
    expect(output).toContain('API_KEY=secret');
  });

  it('reports when no .env files found', () => {
    const output = runCLI('list', tmpDir);
    expect(output).toContain('No .env files found');
  });

  it('truncates long values', () => {
    const longValue = 'a'.repeat(60);
    fs.writeFileSync(path.join(tmpDir, '.env'), `LONG_KEY=${longValue}`);

    const output = runCLI('list', tmpDir);

    expect(output).toContain('LONG_KEY=');
    expect(output).toContain('...');
    expect(output).not.toContain(longValue);
  });

  it('excludes .env.example from listing', () => {
    fs.writeFileSync(path.join(tmpDir, '.env'), 'PORT=3000');
    fs.writeFileSync(path.join(tmpDir, '.env.example'), 'EXAMPLE_KEY=');

    const output = runCLI('list', tmpDir);

    expect(output).toContain('PORT=3000');
    expect(output).not.toContain('EXAMPLE_KEY');
  });
});

describe('CLI: version', () => {
  it('shows version from package.json', () => {
    const pkg = JSON.parse(
      fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf-8')
    );
    const output = runCLI('--version', __dirname);
    expect(output.trim()).toBe(pkg.version);
  });
});
